name: kasanipedido
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_screenutil:
  flutter_svg:
  flutter_calendar_carousel: ^2.4.3
  timeline_tile: ^2.0.0
  table_calendar:
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  meta: ^1.11.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  products_api_impl:
    path: packages/products_api_impl
  products_api:
    path: packages/products_api
  shopping_cart_repository:
    path: packages/shopping_cart_repository
  equatable: ^2.0.5
  intl: ^0.18.1
  dio: ^5.5.0+1
  firebase_core: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/images/
    - assets/icons/

